version: '3.8'

services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    networks:
      - eshop

  CatalogService:
    container_name: CatalogService
    build:
      context: ./CatalogService
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - 5012:5012
    networks:
      - eshop
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  mongodbdata:

networks:
  eshop:
    driver: bridge